# 欢迎来到 Jekyll！
#
# 此配置文件用于影响整个站点的设置，这些值
# 你只需设置一次，之后很少需要再编辑。
# 由于技术原因，当你使用
# `jekyll serve -l -H localhost` 时，此文件*不会*自动重新加载。如果你修改了此文件，请重启
# 服务器进程。

# 基本站点设置
locale                   : "en-US"
site_theme               : "default" # 可用的主题选项有 "default"、"air"、"sunrise"、"mint"、"dirt" 和 "contrast"
title                    : "你的名字 / 站点标题"
title_separator          : "-"
name                     : &name "你的名字"
description              : &description "你的名字的学术作品集"   # 用站点的一般描述更新此项，这是未被子页面覆盖时的默认描述
url                      : https://academicpages.github.io # 站点的基础主机名和协议，例如 "https://[你的 GitHub 用户名].github.io"，
                                                           # 或者如果你已经在 Github 上有其他页面，则使用 "https://[你的 GitHub 用户名].github.io/[你的仓库名]"
baseurl                  : "" # 站点的子路径，例如 "/blog"
repository               : "academicpages/academicpages.github.io"

# 站点作者 - 以下内容控制侧边栏中作者内容的显示。
#               如果某个字段为空，则对应的图标和链接不会显示，否则将会显示。
#               可以通过编辑 /_includes/author-profile.html 进行更多自定义
author:
  # 个人信息
  avatar           : "profile.png"
  name             : "你的侧边栏名称"
  pronouns         : # 示例："she/her"（她/她的）
  bio              : "左侧边栏的简短个人简介"
  location         : "地球"
  employer         : "红砖大学"
  uri              : # URL
  email            : "none@example.org" 

  # 学术网站
  academia         : # URL
  arxiv            : # URL - 更新为你的个人资料的正确链接
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            : "https://orcid.org/yourorcidurl"
  semantic         : # URL
  ssrn             : # URL
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL
  scopus           : # URL
  zotero           : # URL


  # 代码仓库与软件开发
  bitbucket        : # 用户名 - 更新为你在该网站的用户名
  codepen          : # 用户名
  dribbble         : # 用户名
  github           : "academicpages"
  kaggle           : # 用户名  
  stackoverflow    : # 用户编号或用户编号和名称（例如，使用 "1" 或 "1/jeff-atwood"）    

  # 社交媒体
  artstation       : # 用户名
  bluesky          : "bsky.app" # 替换为你的 Bluesky 用户名
  facebook         : # 用户名
  flickr           : # 用户名
  foursquare       : # 用户名
  goodreads        : # 用户名
  google_plus      : # 用户名
  keybase          : # 用户名
  instagram        : # 用户名
  lastfm           : # 用户名
  linkedin         : # 用户名
  mastodon         : # URL
  medium           : # URL
  pinterest        : # 用户名
  soundcloud       : # 用户名
  steam            : # 用户名
  telegram         : # URL
  tumblr           : # 用户名
  twitter          : # X / Twitter 用户名
  vine             : # 用户名
  weibo            : # 用户名
  wikipedia        : # 用户名
  xing             : # 用户名
  youtube          : # 用户名
  zhihu            : # 用户名

# 出版物分类 - 以下是出版物分类列表及其标题
publication_category:
  books:
    title: '书籍'
  manuscripts:
    title: '期刊论文'    
  conferences:
    title: '会议论文'

# 站点设置
teaser                   :  # 预告图片的文件名，放置在 /images/ 目录中，用于社交媒体预览的备用预告图
breadcrumbs              : false # true（启用）, false（禁用，默认）
words_per_minute         : 160
future                   : true
read_more                : "disabled" # 如果启用，会在摘要处添加"阅读更多"链接
talkmap_link             : false      # 改为 true 以在演讲页面添加 talkmap 链接
comments:
  provider               : # false（默认）、"disqus"、"discourse"、"facebook"、"google-plus"、"staticman"、"custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 ，例如：meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5（默认）
    colorscheme          : # "light"（默认）、"dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master"、"gh-pages"
  commitMessage          : "新评论。"
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601"（默认）、"timestamp-seconds"、"timestamp-milliseconds"
atom_feed:
  hide                   : false     # 改为 true 以隐藏页脚中的 RSS 订阅链接
  path                   : # 留空（默认）使用 feed.xml


# SEO 相关
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# 社交分享
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # 社交媒体默认站点图片
og_description           :  # 社交媒体默认站点图片描述
# 用于指定社交资料
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person（个人）或 Organization（组织）（默认为 Person）
  name                   : # 如果用户或组织名称与站点名称不同
  links: # 社交资料链接数组


# 统计分析
analytics:
  provider               :  "false" # false（默认）、"google"、"google-universal"、"google-analytics-4"、"custom"
  google:
    tracking_id          :


# 文件读取
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# 转换
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown 处理
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# 这些设置控制模板使用的集合类型
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# 这些设置控制页面和集合如何被纳入站点
defaults:
  # _posts（文章）
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages（页面）
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching（教学）
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications（出版物）
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio（作品集）
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks（演讲）
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# 输出
permalink: /:categories/:title/
# paginate: 5 # 每页显示的文章数量
# paginate_path: /page:num/
timezone: Etc/UTC # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# 插件
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# 使用 --safe 模式模拟 GitHub Pages
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji


# 归档
#  类型
#  - 使用 Liquid 构建的 GitHub Pages 兼容归档页面 ~> type: liquid（默认）
#  - Jekyll Archives 插件归档页面 ~> type: jekyll-archives
#  路径（示例）
#  - 使用 Liquid 方法时，归档页面应存在于指定路径，否则可能会出现
#    死链（尤其是在启用面包屑导航的情况下）
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML 压缩
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
